### PR TITLE
Sync master with upstream

### PR DESCRIPTION
**Pull request by geoffreychiou**
@130s please review.

### CODE REVIEW

**Review by 130s — COMMENTED** [review]
- There's a quite number of commits and those don't look new that were merged after the latest release in the upstream. Can you explain what you're trying?
- This is an optional thing to do after fixing the issue with our app but if you were able to find what's causing our issue, better to fix upstream and ask for a new release?

**Comment by geoffreychiou** [comment]
> There's a quite number of commits and those don't look new that were merged after the latest release in the upstream. Can you explain what you're trying?

Our copy of master was behind, I am syncing it with upstream.

> This is an optional thing to do after fixing the issue with our app but if you were able to find what's causing our issue, better to fix upstream and ask for a new release?

We can do that, but this is holding up our internal projects so this is a temporary fix. (I don't know how long a release takes).

This pull only brings our fork up to date with upstream/master.

**Review by 130s — APPROVED** [review]
I see. I briefly looked at the upstream and there are many more newer commits but I assume you've stopped syncing before suspicious commits.

**Comment by shaun-edwards** [comment]
Are these changes the same?  This [one](https://github.com/plusone-robotics/rosparam_handler/pull/2/commits/8251d472ee8a901e1891fdb9a2aeaa1633e75a5e) and this [one](https://github.com/plusone-robotics/rosparam_handler/commit/5e511fb95b2d3dac163aec91c9925068dc55e628).  If so, should we do a `force push` to keep us in better sync with upstream?

**Comment by geoffreychiou** [comment]
> Are these changes the same? This one and this one. If so, should we do a force push to keep us in better sync with upstream?

It would be a lot neater if we just force pushed a copy of cbandera/master into ours.

**Comment by geoffreychiou** [comment]
We're going to force push.

**Comment by 130s** [comment]
> It would be a lot neater if we just force pushed a copy of cbandera/master into ours.

I'm not sure what "force push" means here but I'll leave that up to y'all.

**Pull request closed without merging**
